services:
  db:
    image: postgres:latest
    container_name: "database"
    restart: on-failure
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ".env.dev"
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data