services:
  db:
    image: postgres:latest
    container_name: "database"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
#    ports:
#      - "5432:5432"
    env_file:
      - ".env.dev"
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
#    ports:
#      - "6379:6379"
    volumes:
      - redis_data:/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "baddman@list.ru"
      PGADMIN_DEFAULT_PASSWORD: "Apple123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin: