services:
  db:
    image: postgres:latest
    container_name: "database"
    hostname: "database"
    restart: always
    volumes:
      - ./postgres_data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ".env.dev"

  redis:
    image: redis:latest
    container_name: "redis"
    hostname: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq_data/data/:/var/lib/rabbitmq/
        - ./rabbitmq_data/log/:/var/log/rabbitmq

